[WIP] 测试框架 v0.1
J-ZhengLi/rim pull request #183
Opened 2024-12-19 09:51 UTC by LuuuXXX

2025-01-06 09:53 UTC, J-ZhengLi requested changes
~

改完之后记得完整走一下发版流程：
```bash
cargo dev vendor
cargo dev dist
```
正常情况会在dist目录下生成当前target的目录，目录下有 `xuanwu-rust-installer`, `xuanwu-rust-installer-cli` 以及离线包目录，并且离线包里包含上述两个二进制以及 `packages` 目录，`packages` 目录下包含`dist`子目录（包含工具链安装包及 channel-rust-manifest）, <target>子目录，详情参考 `resources/packages.txt` 文件

2025-01-06 09:53 UTC, J-ZhengLi commented on Cargo.toml
> +
```diff
+rim-test-support = { path = "rim_test/rim-test-support" }
-rim-test-support.workspace = true
-snapbox.workspace = true
```

2025-01-06 09:53 UTC, J-ZhengLi commented on rim_test/rim-test-macro/src/lib.rs
> +            "should_ignore" => {
nit: 用 `ignore`更贴切

2025-01-06 09:53 UTC, J-ZhengLi commented on rim_test/rim-test-support/Cargo.toml
> +snapbox.workspace = true
```diff
-rim-test-macro.workspace = true
+rim-test-macro = { path = "../../rim_test/rim-test-macro" }
anyhow.workspace = true
-snapbox.workspace = true
+snapbox = { version = "0.6.20", features = ["dir"] }
```

2025-01-06 09:53 UTC, J-ZhengLi commented on rim_test/rim-test-support/src/paths.rs
> +}
用 `tempfile`, 最终返回 `tempfile::TempDir`, 这样就不用 `TestPathExt` 自己创建/清空目录了，并且跑完自动删除。
注意 `TempDir` drop之后会自动删除对应目录

2025-01-06 09:53 UTC, J-ZhengLi commented on rim_test/rim-test-support/src/paths.rs
> +}
这个函数返回 `test_root`, 连着上一条建议使用 `TempDir` 作为返回类型

2025-01-06 09:53 UTC, J-ZhengLi commented on rim_test/rim-test-support/src/project.rs
> +    }
多余了，rim-cli 和 installer-cli 功能是一样的

2025-01-13 07:13 UTC, LuuuXXX commented on rim_dev/src/vendor.rs
> +    .join("resources");
最初的设计 后面忘记改了

2025-01-21 03:33 UTC, J-ZhengLi commented on rim_dev/src/vendor.rs
> -
这个不要删，pkg_dir 目录在新环境下不存在

2025-01-21 06:02 UTC, J-ZhengLi commented on .github/workflows/standard-tests.yml
> +        run: bash ci/run.sh
哦对了，standard-test只测核心功能，不测gui部分。把这块加到gui-test里面，不然的话没有gui部分的改动也要多跑这十几分钟测试，很浪费时间

2025-01-21 06:13 UTC, J-ZhengLi approved these changes

2025-01-21 06:14 UTC, merged